### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ghost** [MattZ45986/Bombsquad_mods#1]
I found some bugs on this mods :

SimonSays.py (I cant play this mod)
Flag Day.py
Basketball.py
JumpingContest.py (I cant play this mod)
WizardWar.py (I cant play this mod)

Most of the 5 mods i listed, I really cant play them. Everytime the game starts it doesnt shows the character. This is the, JumpingContest.py, WizardWar.py and SimonSays.py

In Basketball, please remove the popping message whenever i tap the HOLD button because the whole game is full with coordinates. Sometimes I cant play the game too.

In Flag Day, sometimes the player repeating. And the player dies automatically without even touching or grabbing any of the flags, and the other play starts repeating in the game. Some players cant play anymore. Also please add some scoring limit.

If you have time to spare, can you please fix this mods? I would love to see this fix because your mods are really great.

**Comment by MattZ45986** [comment]
@Esie-Eyen, welcome to GitHub and thank you so much for your feedback.  I have been developing these mods for a while hoping to push them to the official mod manager.  [I am not done with them as you could probably tell.]  I am still in the testing stages of FlagDay and Basketball, so those are both glitches I know about. However, I am not sure what is going on with WizardWar or JumpingContest as the latter works perfectly for me, and the prior is bug-free. It's even on the official mod manager approved by @Mrmaxmeier.  If you could give me a bit more detail about those glitches it would be greatly appreciated. (I found the problem in SimonSays and it should be working if you want to try it out!)  Once again, thank you for your feedback and encouragement, I will see to it that any problem you have is fixed.

<If you have any mod ideas of your own, please let me know. I'm always looking for fun ideas.>

**Comment by ghost** [comment]
@MattZ45986 Hello again, SimonSays works properly now. And yeah as I said I still have problem on WizardWar and JumpingContest. I dont know the problem, everytime I join or play the game it just shows the map and the arrow whenever I move the moving pad. I cant see my character. Should I play this with 2 players?

**Comment by MattZ45986** [comment]
Alright, I did my best to fix Jumping Contest.  It would be helpful to know which mode you were playing on:  eams/FFA/Co-op. That way I can play it in the same mode as you to see where the problem lies.  (I made it compatible for all three)

**Comment by ghost** [comment]
@MattZ45986 Thank you! Now I can play this minigame. It is really fun, I might as well check your other mods.

**Comment by MattZ45986** [comment]
I recommend Paint.py for one-player, or with friends Plague.py and SharksAndMinnows.py are fun.

I'm glad you enjoy the mods, @Esie-Eyen , please let me know if anything else goes awry.

**Comment by ghost** [comment]
@MattZ45986 Another request, I have problems in Plague and WizardWar Mod. Ive already told you about the WizardWar, about Plague players can join but nothing happens after that. And I also have problem in SimonSays again, it commands sometime that we should be out of circle but when we are going out the circle everybody dies and one player only remain. It works sometimes but everyone dies even though we follows the command. Please spare some time on this, anyway thanks for responding and fixing the mods. My friends enjoys the Basketball and Simon Says.

**Comment by MattZ45986** [comment]
When you say that everyone dies when you run out of the circles, is the command "run outside of the circles", or "Simon says run outside of the circles." Because you are only supposed to when Simon says to.  When it says out of the circles, it means out of all colored circles. I just tested it and everything works.  

As to the glitch in Wizard War, I need to know which play-mode you are in: FFA, Teams, or Co-op.  I just changed the mod so that it doesn't work in Co-op, because it wouldn't make much sense.  Again, I tried it and it works. (Maybe you are trying outdated versions?)

For Plague, players use only bombs, so try throwing bombs.

By the way, I'm just wondering how it is you are putting my mods on your game, just so I know how to give instructions for others. Thanks!

**Comment by ghost** [comment]
Thank you @MattZ45986 , I didnt notice the rule of the Simon Says.

I play all the games in FFA except Basketball.

I download your mods by downloading it RAW. So i think it is the latest version.

For Plague, bombs dont work.

One more thing I quite dont understand Sharks and Minnows. Idk how to get score when I am the white person, and black can easily dominates the game.

**Comment by MattZ45986** [comment]
@Esie-Eyen , Sharks and Minnows is a game where there is a group of minnows and a group of sharks.  The minnows (the guys in the circle) try to run back and forth across the map without getting caught by the sharks (the guys in the middle).  Minnows get 10 points for crossing, sharks get 20 points for catching a minnow not on their team, and for teams mode sharks get 5 points for catching a minnow of their color.

Thank you for clearing up my previous questions. I am puzzled as to why the plague bombs aren't working. They are supposed to detonate and curse anyone in their blast radius. (Or do you mean that you can't even throw bombs?)
![sharks and minnows](https://user-images.githubusercontent.com/33816924/44174226-6ee52780-a0b0-11e8-96e3-41c6ba8f5832.png)

**Comment by ghost** [comment]
@MattZ45986 I cant throw bombs whenever I try to in Plague, nothing happens I can just walk. Everything works perfectly in other mods.

**Comment by Gengar-lab** [comment]
Please give link yo download them because they are not working.

**Comment by ghost** [comment]
@Benefit-Zebra I answered this question, see it on https://github.com/MattZ45986/Bombsquad_mods/issues/3

**Comment by Gengar-lab** [comment]
@MattZ45986 In Flag Day when player dies it shows "<bs.player object at ......>" on the screen , it irritates  when the player dies because of wrong flag.

**Comment by MattZ45986** [comment]
@Benefit-Zebra, I sometimes put debug statements in the code to test functionality. If you redownload the mod it should work now.

**Comment by Esie-Eyen** [comment]
Gravity Falls Bugs:
- The no gravity mode works only once. (Once you died and respawn the gravity backs to normal.)
- Some maps is not compatible for the mod. (I recommend only closed maps)

(I really enjoy the mod, If possible can you fix the Plague mod?)

**Comment by ghost** [comment]
Hey @MattZ45986 can you fix this?

Gravity Falls Bugs:
- The no gravity mode works only once. (Once you died and respawn the gravity backs to normal.)
- Some maps is not compatible for the mod. (I recommend only closed maps)

Plague Bugs:
- I cant do anything, bomb, punch or even grab.
